spring:
  datasource:
    url: jdbc:mysql://localhost:3306/coursedb
    username: root
    password: geezie0Eiph1lalee2ohrahn6gah4Ash
  jpa:
    generate-ddl: true
    database-platform: org.hibernate.dialect.MySQL55Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL55Dialect
        format_sql: true
        generate_statistics: true
        cache:
          use_query_cache: false
          use_second_level_cache: true
          region.factory_class: jcache
          provider: org.ehcache.jsr107.EhcacheCachingProvider
logging:
  level:
    org.springframework:
      cache: TRACE