spring:
  datasource:
    url: jdbc:mysql://192.168.99.100:43306/coursedb
    username: root
    password: admin@123
  jpa:
    generate-ddl: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        generate_statistics: true