spring:
  datasource:
    url: jdbc:mysql://192.168.99.100:3306/coursedb
    username: root
    password: 1234
  jpa:
    generate-ddl: true
    database-platform: org.hibernate.dialect.MySQL5Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        generate_statistics: true
        cache:
          use_query_cache: true
          use_second_level_cache: true
          region.factory_class: org.hibernate.cache.ehcache.EhCacheRegionFactory
logging:
  level:
    org.springframework:
      cache: TRACE